-- vim.cmd("colorscheme gruvbox")
vim.cmd("colorscheme catppuccin-mocha")
-- vim.cmd("set background=light")

-- highlights
-- vim.cmd("hi Visual guibg=darkblue gui=none")
-- vim.cmd("hi Normal guibg=none")
-- vim.cmd("hi NormalNC guibg=none")
-- vim.cmd("hi NormalFloat guibg=none")
vim.cmd("hi NonText  guifg=#333333")
-- vim.cmd("hi SignColumn guibg=none")
-- vim.cmd("hi Visual gui=none guibg=yellow")
-- vim.cmd("hi CursorLine gui=none guibg=#131b25")
-- vim.cmd("hi ColorColumn guibg=darkred ctermbg=none")
vim.cmd("hi LineNr guibg=none ctermbg=none guifg=#9aae6b")
vim.cmd("hi LineNrBelow guibg=none ctermbg=none guifg=#444444")
vim.cmd("hi LineNrAbove guibg=none ctermbg=none guifg=#444444")
